### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [shelbycollopy/codecademy-api-capstone-expresso#7]
[Exceeds Expectations] Brilliant work! 

I was able to:

- add menu items
- remove menu items
- update menu items
- add employees
- update employees
- delete employees
- add timesheets
- remove timesheedts
- update timesheets
- rename menus
- add menus
- remove menus

You did well with keeping your code clean and easy to navigate by having consistent indentation, descriptive comments, descriptive file names, and using whitespace effectively. Furthermore, all the tests passed! In addition, your git commit messages are informative. Overall, fantastic work. You killed it. 🔥 

git commit messages: https://github.com/shelbycollopy/codecademy-api-capstone-expresso/commits/master

**Comment by shelbycollopy** [comment]
Thanks for the feedback! This was a fun project. I really liked combining my knowledge of JavaScript, SQL and Node.
